
steps:
# Build the backend container image
- name: 'docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/images/backend', '-f', 'backend/Dockerfile', 'backend' ]
  id: build-backend

# Build the frontend container image
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [ '-c', 'docker build --build-arg AUTH0_CLIENTID=$$AUTH0_CLIENTID -t europe-west1-docker.pkg.dev/$PROJECT_ID/images/frontend -f frontend/Dockerfile frontend' ]
  secretEnv: ['AUTH0_CLIENTID']
  id: build-frontend
  waitFor: ['-']


# Push the backend container image to Container Registry
- name: 'docker'
  args: [ 'push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/images/backend']
  id: push-backend
  waitFor:
    - build-backend

# Push the frontend container image to Container Registry
- name: 'docker'
  args: [ 'push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/images/frontend']
  id: push-frontend
  waitFor:
    - build-frontend


# Deploy backend container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'backend', '--image', 'europe-west1-docker.pkg.dev/$PROJECT_ID/images/backend', '--region', 'europe-west1', '--allow-unauthenticated', '--port=80', '--update-env-vars', 'ENVIRONMENT=tme,AUTH0_AUDIENCE=https://api.trigpointing.me,AUTH0_DOMAIN=teasel.eu.auth0.com']
  id: deploy-backend
  waitFor:
    - push-backend

# Deploy frontend container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'frontend', '--image', 'europe-west1-docker.pkg.dev/$PROJECT_ID/images/frontend', '--region', 'europe-west1', '--allow-unauthenticated', '--port=80']
  id: deploy-frontend
  waitFor:
    - push-frontend

# Get secrets (technically the clientid is not secret, and is included in the final build image, but still don't want it in github )
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/tme-vue-clientid/versions/latest
    env: AUTH0_CLIENTID

images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/images/backend'
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/images/frontend'

# You can organize your builds with tags
# tags: ['gcp-cloud-build-backend-build']
