version: '3.6'
services:
  db:
    # image: postgres
    image: postgis/postgis
    restart: always
    ports:
      - "5432:5432"
    environment:
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: verysecret
      POSTGRES_DB: tuk
